using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FootballManager.Enums
{
    public enum Country
    {
        Albania,
        Algeria,
        Argentina,
        Australia,
        Austria,
        Belgium,
        BosniaAndHerzegovina,
        Brazil,
        Bulgaria,
        Cameroon,
        Canada,
        Chile,
        China,
        Colombia,
        CostaRica,
        Croatia,
        CzechRepublic,
        Denmark,
        Ecuador,
        Egypt,
        England,
        Finland,
        France,
        Germany,
        Ghana,
        Greece,
        Honduras,
        Hungary,
        Iceland,
        Iran,
        Ireland,
        Israel,
        Italy,
        IvoryCoast,
        Jamaica,
        Japan,
        Mexico,
        Morocco,
        Netherlands,
        NewZealand,
        Nigeria,
        NorthernIreland,
        Norway,
        Panama,
        Paraguay,
        Peru,
        Poland,
        Portugal,
        Qatar,
        Romania,
        Russia,
        SaudiArabia,
        Scotland,
        Senegal,
        Serbia,
        Slovakia,
        Slovenia,
        SouthAfrica,
        SouthKorea,
        Spain,
        Sweden,
        Switzerland,
        Tunisia,
        Turkey,
        Ukraine,
        UnitedStates,
        Uruguay,
        Venezuela,
        Wales
    }
}